Repository AliceO2Group/AliceO2, pull requests merged in 2024-07, with the labels that each got.

#13282 Fixes of bugs in class mask calculation
  Detectors/CTP/simulation/src/Digitizer.cxx
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

#13290 Fix return value for rANS packing bug recovery
  DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/EncodedBlocks.h
Labels: async-2023-pbpb-apass4, async-2024-pp-apass1, async-2024-pp-cpass0

#13250 AOD: Add thinner option to producer
  Detectors/AOD/include/AODProducerWorkflow/AODProducerWorkflowSpec.h
  Detectors/AOD/src/AODProducerWorkflowSpec.cxx
Labels: async-2023-pbpb-apass4

#13286 Improved treatment of recursive defines
  scripts/datamodel-doc/ALICEO2dataModelTools.py
  scripts/datamodel-doc/ALICEO2includeFile.py
  scripts/datamodel-doc/extractDataModel.py
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

#13339 GLO: Revert changes on CMakeLists
  Detectors/GlobalTracking/CMakeLists.txt
Labels: async-2023-pbpb-apass4
