Repository AliceO2Group/AliceO2, pull requests merged in 2024-12, with the labels that each got.

#13757 Fixes to propagate updates of GPU params (D.Rohr)
  GPU/GPUTracking/DataTypes/GPUNewCalibValues.cxx
  GPU/GPUTracking/Global/GPUChainTracking.cxx
Labels: async-2024-pp-apass1, async-2024-PbPb-cpass0, async-2024-PbPb-apass1, async-2024-ppRef-apass1

#13762 Optionally select CTFs in timestamps or orbits range
  Common/Utils/include/CommonUtils/IRFrameSelector.h
  Common/Utils/src/IRFrameSelector.cxx
  Detectors/CTF/README.md
  Detectors/CTF/workflow/include/CTFWorkflow/CTFReaderSpec.h
  Detectors/CTF/workflow/src/CTFReaderSpec.cxx
  Detectors/CTF/workflow/src/ctf-reader-workflow.cxx
Labels: async-2024-PbPb-apass1

#13773 ITS: protect trackleting from exceeding maximum nROFs in weird situations
  Detectors/ITSMFT/ITS/tracking/src/TrackerTraits.cxx
Labels: async-2024-PbPb-apass1, async-2024-ppRef-apass1

#13777 AOD: Missing default init
  Detectors/AOD/include/AODProducerWorkflow/AODProducerWorkflowSpec.h
Labels: async-2024-PbPb-apass1, async-2024-ppRef-apass1

#13789 DCAFitterN: log-throttling for err.messages + user policy for bad CovMat
  Common/DCAFitter/README.md
  Common/DCAFitter/include/DCAFitter/DCAFitterN.h
Labels: async-2024-PbPb-apass1, async-2024-ppRef-apass1

#13785 Bump trackextra table to the latest version
  Detectors/AOD/src/AODProducerWorkflowSpec.cxx
  Framework/Core/include/Framework/AnalysisDataModel.h
  Framework/Core/src/AODReaderHelpers.cxx
  Framework/Core/test/test_AnalysisTask.cxx
Labels: async-2024-PbPb-apass1, async-2024-ppRef-apass1

#13802 Fix type for entry in MCEventHeader
  Generators/src/GeneratorPythia8.cxx
Labels: Simulation

#13801 HybridGen/EventPool: small fixes, Add missing EventHeader propagation
  Generators/include/Generators/BoxGenerator.h
  Generators/include/Generators/Generator.h
  Generators/include/Generators/GeneratorFromFile.h
  Generators/include/Generators/GeneratorHybrid.h
  Generators/src/GeneratorFromFile.cxx
  Generators/src/GeneratorHybrid.cxx
Labels: Simulation

#13784 fix in track propagation to TOF for MC
  DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoTOF.h
  DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoTOFReco.h
  Detectors/GlobalTracking/include/GlobalTracking/MatchTOF.h
  Detectors/GlobalTracking/src/MatchTOF.cxx
Labels: async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-ppRef-apass1

#13815 Make tpc-time-series to accept track sources
  Detectors/TPC/workflow/include/TPCWorkflow/TPCTimeSeriesSpec.h
  Detectors/TPC/workflow/src/TPCTimeSeriesSpec.cxx
  Detectors/TPC/workflow/src/tpc-time-series.cxx
  prodtests/full-system-test/calib-workflow.sh
Labels: async-2024-PbPb-apass1, async-2024-ppRef-apass1
