Repository AliceO2Group/AliceO2, pull requests merged in 2024-10, with the labels that each got.

#13547 TPC: Optimising scaling of distortions in MC
  Detectors/TPC/simulation/src/Digitizer.cxx
  Detectors/TPC/spacecharge/include/TPCSpaceCharge/SpaceCharge.h
  Detectors/TPC/spacecharge/src/SpaceCharge.cxx
Labels: async-2023-pbpb-apass4

#13546 Make sure that the string 'using' in a text is NOT interpreted as the using keyword.
  scripts/datamodel-doc/ALICEO2includeFile.py
Labels: async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

#13227 [EMCAL-539,EMCAL-696,EMCAL-697] FIT-CTP-EMCAL trigger simulation
  Detectors/CTP/simulation/src/Digitizer.cxx
  Detectors/EMCAL/simulation/CMakeLists.txt
  Detectors/EMCAL/simulation/include/EMCALSimulation/DigitizerTRU.h
  Detectors/EMCAL/simulation/include/EMCALSimulation/LZEROElectronics.h
  Detectors/EMCAL/simulation/src/DigitizerTRU.cxx
  Detectors/EMCAL/simulation/src/DigitsWriteoutBufferTRU.cxx
  Detectors/EMCAL/simulation/src/LZEROElectronics.cxx
  Detectors/EMCAL/workflow/include/EMCALWorkflow/EMCALDigitizerSpec.h
  Detectors/EMCAL/workflow/src/EMCALDigitizerSpec.cxx
Labels: stale
