Repository AliceO2Group/AliceO2, pull requests merged in 2024-04, with the labels that each got.

#12889 ITS efficiency maps protection for digitization out of range
  DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/TimeDeadMap.h
  Detectors/ITSMFT/common/workflow/src/DeadMapBuilderSpec.cxx
Labels: async-mc

#12920 More flexibel use of event setup from collisioncontext
  Common/SimConfig/include/SimConfig/SimConfig.h
  Common/SimConfig/src/SimConfig.cxx
Labels: async-2023-pbpb-apass, async-2023-pp-apass1, async-2022-pp-apass6, async-2022-pp-apass4, async-mc, async-data

#12954 More consistent MCHeader forwarding when using GeneratorFromFile
  Common/Utils/include/CommonUtils/RootSerializableKeyValueStore.h
  Generators/src/GeneratorFromFile.cxx
Labels: async-2022-pp-apass6

#13000 Digitization: Fix timestamps for querying CCDB when using BasicCCDBMa…
  Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
Labels: async-2023-pbpb-apass, async-2023-pp-apass1, async-2022-pp-apass6-2023-PbPb-apass2, async-2022-pp-apass4, async-mc, async-data

#13062 Account ITS/MFT ROF start shift in AOD ITS/MFT standalone tracks time
  Detectors/AOD/include/AODProducerWorkflow/AODProducerWorkflowSpec.h
  Detectors/AOD/src/AODProducerWorkflowSpec.cxx
Labels: async-2023-pbpb-apass4

#13100 V0: Fix wrong V0 Photon TPConly cut
  Detectors/Vertexing/src/SVertexer.cxx
Labels: async-2023-pbpb-apass4
