Repository AliceO2Group/AliceO2, pull requests merged in 2024-03, with the labels that each got.

#12792 Discard afterburner tracks
  Detectors/GlobalTracking/src/MatchITSTPCQC.cxx
Labels: async-2023-pbpb-apass, async-data

#12505 TRD shift tracklet position by one pad
  DataFormats/Detectors/TRD/include/DataFormatsTRD/Tracklet64.h
  Detectors/TRD/base/include/TRDBase/TrackletTransformer.h
  Detectors/TRD/base/src/TrackletTransformer.cxx
  Detectors/TRD/calibration/include/TRDCalibration/PulseHeight.h
  Detectors/TRD/calibration/include/TRDCalibration/TrackBasedCalib.h
  Detectors/TRD/calibration/src/PulseHeight.cxx
  Detectors/TRD/calibration/src/TrackBasedCalib.cxx
  Detectors/TRD/qc/include/TRDQC/Tracking.h
  Detectors/TRD/qc/src/Tracking.cxx
  Detectors/TRD/workflow/include/TRDWorkflow/TRDGlobalTrackingQCSpec.h
  Detectors/TRD/workflow/include/TRDWorkflow/TRDPulseHeightSpec.h
  Detectors/TRD/workflow/src/TRDTrackletTransformerSpec.cxx
  Detectors/TRD/workflow/src/TrackBasedCalibSpec.cxx
Labels: stale

#12841 Set TRD forward pileup margin to 80 BCs
  GPU/GPUTracking/Definitions/GPUSettingsList.h
Labels: async-2023-pbpb-apass, async-data

#12866 GPU TPC: Add extra cluster errors for CSide Sector 1/2
  GPU/GPUTracking/Base/GPUParam.cxx
  GPU/GPUTracking/Base/GPUParam.h
  GPU/GPUTracking/Base/GPUParam.inc
  GPU/GPUTracking/Base/GPUReconstructionCPU.cxx
  GPU/GPUTracking/Base/GPUReconstructionCPU.h
  GPU/GPUTracking/Definitions/GPUSettingsList.h
  GPU/GPUTracking/Global/GPUChainTrackingSliceTracker.cxx
  GPU/GPUTracking/Merger/GPUTPCGMMergerDump.cxx
  GPU/GPUTracking/Merger/GPUTPCGMPropagator.cxx
  GPU/GPUTracking/Merger/GPUTPCGMPropagator.h
Labels: async-2023-pbpb-apass
