Repository AliceO2Group/AliceO2, pull requests merged in 2024-11, with the labels that each got.

#13660 Update TPC scaling when MeanLumiRef changed
  GPU/TPCFastTransformation/CorrectionMapsHelper.h
Labels: mc, async-2024-PbPb-apass1

#13687 Protect LT-int.calculation in TRD refit from bad TPC correction
  Detectors/TRD/workflow/src/TRDGlobalTrackingSpec.cxx
Labels: mc, async-2024-PbPb-cpass0, async-2024-PbPb-apass1, async-2024-ppRef-apass1

#13688 ParticleDatabase: Added particle a2(1320) in the O2Database accroding to latest PDG
  DataFormats/simulation/include/SimulationDataFormat/O2DatabasePDG.h
  Steer/src/O2MCApplication.cxx
Labels: async-2023-pbpb-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-PbPb-apass1

#13719 Object to provide TB to cut due to the Altro sync. procedure
  DataFormats/Detectors/TPC/CMakeLists.txt
  DataFormats/Detectors/TPC/include/DataFormatsTPC/AltroSyncSignal.h
  DataFormats/Detectors/TPC/src/DataFormatsTPCLinkDef.h
Labels: async-2023-pbpb-apass4, async-2024-PbPb-cpass0, async-2024-PbPb-apass1, async-2024-ppRef-apass1

#13729 Add AltroSyncSignal to TPC CDBTypeMap
  Detectors/TPC/base/include/TPCBase/CDBTypes.h
Labels: async-2024-pp-apass1, async-2024-PbPb-apass1

#13734 Fix in the parsing of ccdb-run-dependent options
  Framework/Core/src/DataDescriptorQueryBuilder.cxx
Labels: async-2024-pp-apass1, async-2024-PbPb-cpass0, async-2024-PbPb-apass1, async-2024-ppRef-apass1
