Repository AliceO2Group/AliceO2, pull requests merged in 2024-05, with the labels that each got.

#13119 Do not const_cast/modify sh.mem. objetcs from upstream procsesses
  DataFormats/simulation/include/SimulationDataFormat/MCCompLabel.h
  Detectors/GlobalTracking/include/GlobalTracking/TrackCuts.h
  Detectors/ITSMFT/ITS/postprocessing/studies/src/ImpactParameter.cxx
  Detectors/ITSMFT/ITS/postprocessing/studies/src/TrackCheck.cxx
  Detectors/ITSMFT/ITS/tracking/include/ITStracking/ROframe.h
Labels: async-2023-pbpb-apass4

#13147 mch-digit-reader uses --mch-digit-infile and not --infile
  prodtests/full-system-test/dpl-workflow.sh
Labels: async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

#13176 #13173 - fixing DCA for combined tracking + adding nshared clusters
  Detectors/TPC/workflow/src/TPCTimeSeriesSpec.cxx
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2, async-2022-pp-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

#13188 Correctly set WITH_OPENMP to ITS tracking lib
  Detectors/ITSMFT/ITS/tracking/CMakeLists.txt
  Detectors/ITSMFT/ITS/tracking/src/TrackerTraits.cxx
Labels: async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2, async-2022-pp-apass4, async-2022-pp-apass4-accepted, async-2022-pp-apass6-2023-PbPb-apass2-accepted, async-2023-pbpb-apass3-accepted, async-2023-pbpb-apass4-accepted, async-2023-pp-apass4, async-2023-pp-apass4-accepted, async-2024-pp-apass1, async-2024-pp-apass1-accepted, async-2022-pp-apass7, async-2022-pp-apass7-accepted, async-2024-pp-cpass0, async-2024-pp-cpass0-accepted
