Repository AliceO2Group/AliceO2, pull requests merged in 2025-04, with the labels that each got.

#14142 Common: DCAFitter fix collinear not touching calc
  Common/DCAFitter/include/DCAFitter/HelixHelper.h
Labels: async-2024-ppRef-apass1, async-2024-PbPb-apass2, async-2023-PbPb-apass5

#14097 AOD: save selected TPC standalone tracks from thinning
  Detectors/AOD/include/AODProducerWorkflow/AODProducerWorkflowSpec.h
  Detectors/AOD/src/AODProducerWorkflowSpec.cxx
Labels: async-2024-ppRef-apass1, async-2024-PbPb-apass2, async-2023-PbPb-apass5

#13928 Added particle f2(1270) in the O2Database accroding to PDG 2024
  DataFormats/simulation/include/SimulationDataFormat/O2DatabasePDG.h
Labels: async-2023-pbpb-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-PbPb-apass1

#13998 Add PMD info to AO2Ds
  Framework/Core/include/Framework/AnalysisDataModel.h
Labels: stale

#14220 Fix: TrackLTIntegral.addStep needs (q/p)^2 instead of 1/p^2
  DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackLTIntegral.h
  DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackParametrization.h
  DataFormats/Reconstruction/src/TrackLTIntegral.cxx
  DataFormats/Reconstruction/test/testLTOFIntegration.cxx
  Detectors/Base/src/Propagator.cxx
  Detectors/GlobalTracking/src/MatchTPCITS.cxx
  Detectors/TRD/workflow/src/TRDGlobalTrackingSpec.cxx
Labels: async-2024-PbPb-apass2, async-2023-PbPb-apass5
